# Generated by Django 2.0.2 on 2018-02-14 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='b',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
    ]
